DESCRIPTION
R/labeledscatterchart.R
R/scatterchart.R

The changes in this branch is causing diffs in labeledscatter and scatterplot charts in https://github.com/Displayr/flipChartTests2/tree/master/tests/testthat/snapshots/diff - but these changes are actually correct because certain colors in the supplied palette should be skipped when they are not used.
There are currently no tests added to flipStandardCharts, but these tests that are diffing in flipChartTests2 would test the code in this branch after merging

DS-2969: Fix handling of data series in Scatterplot with all missing values 

---

R/barchart.R
R/barmulticolor.R
R/columnchart.R
R/columnmulticolor.R
R/deprecated_standardchart.R
R/distribution.R
R/linechart.R
R/pyramid.R
R/radarchart.R
R/scatterchart.R
R/smallmultiples.R
R/sparkline.R
R/stackedcolumnannot.R

Now that plotly is fixed, and iframeless areachart has appeared to work correctly, convert all standard charts to iframeless

RS-7135: convert all standard charts to iframeless

---

R/areachart.R
R/barchart.R
R/barmulticolor.R
R/columnchart.R
R/columnmulticolor.R
R/deprecated_standardchart.R
R/distribution.R
R/linechart.R
R/pyramid.R
R/radarchart.R
R/scatterchart.R
R/smallmultiples.R
R/sparkline.R
R/stackedcolumnannot.R

For some reason, plotly fixes have disappeared from charts. This is to revert back into iframes, as app visualisations are now buggy

Revert "RS-7135: convert all standard charts to iframeless"

---

R/areachart.R
R/barchart.R
R/barmulticolor.R
R/columnchart.R
R/columnmulticolor.R
R/deprecated_standardchart.R
R/distribution.R
R/linechart.R
R/pyramid.R
R/radarchart.R
R/scatterchart.R
R/smallmultiples.R
R/sparkline.R
R/stackedcolumnannot.R

The iframeless cartesian widgets have issues with their x-axis ticks causing diffs and customer frustration. They are going back into their iframes (again) until this is resolved.

RS-7135: going back to widgets in iframes

---

DESCRIPTION
R/areachart.R
R/barchart.R
R/barmulticolor.R
R/chartutils.R
R/columnchart.R
R/columnmulticolor.R
R/linechart.R
R/palm.R
R/pyramid.R
R/radarchart.R
R/stackedcolumnannot.R
tests/testthat/test-bug-ds3236.R

This PR checks for an extra percentage sign in the data label suffix and values axis tick labels and removes it (no changes are made to the data).

DS-3236: Check there is no extra percentage sign

---

DESCRIPTION
R/geographicmap.R
R/updaterda.R

* Update/override hovertext in `leafletMap` and `plotlyMap` when the user has supplied U.S. regions to `GeographicMap` so that they display U.S. region names instead of U.S. state names (matching the supplied data)
* Fix bug with `us.regions` data.frame in `R/sysdata.rda`: the "Code" (two-letter state abbreviation) for Illinois was incorrectly entered as `"ME"` instead of `"IL"`.

DS-4143: Geographic Maps - Fix hovertext when plotting U.S. regions

---

R/geographicmap.R

This is to fix the problem where leaflet doesn't realise that longitude 179 is close to longitude -179. Affects the maps for New Zealand, Fiji and Russia

RS-13816: adjust polygons as well as default zoom to wrap around antimeridian

---

DESCRIPTION
R/timeseries.R
tests/testthat/test-timeseries.R

Applying as.character to a POSIXt object can now strip the time portion of the text if it is identical to 00:00:00. This is new behavior in R4.3.0

DS-4185: Avoid repeated coercion of characters to dates

---

DESCRIPTION

sf is required by the deprecation of certain other packages upon which the sp spatial mapping package requires. Adding the dependency should ensure that sp continues to work.

!untracked: Add strong dependency for sf package

---

DESCRIPTION
R/chartutils.R
tests/testthat/test-timeaxis.R

Previous commit fixed tick label spacing for monthly intervals which have different number of days. However, this overwrote the default behaviour when the dates are the first day of every month (tick labels should only show months without days).

RS-15119: Fix change in default tick format due to last commit

---

.circleci/config.yml
DESCRIPTION
R/geographicmap.R

This PR fixes the blank output caused be updating leaflet from version 2.1.2 to 2.2.0. It is caused by this change: https://github.com/rstudio/leaflet/pull/817

FS2-1973: Check for existing dependencies before appending css

---

DESCRIPTION
R/chartutils.R

Fixes a problem that I noticed from yesterday's diffs where no gridline was drawn at zero when the user has not specified a zeroline

FS2-2309: Draw gridline at zero if there is no zeroline

---

DESCRIPTION
R/combinedscatterplot.R
man/CombinedScatter.Rd

Added defaults for legend.title and legend.bubble.title. Legend.bubble.title used to be automatically set to scatter.sizes.name but for consistency with the others, its nicer to have the title as a separate parameter

FS2-2716: automatically populate legend.title

---

R/combinedscatterplot.R

Fixes a bug when the background color is translucent and the plot area ends up being darker as there is a double up of the background color. By not specifying `plot.background.color`, the default of 'transparent' is used.

FS2-2756: Fix background color bug

---

.circleci/config.yml
tests/testthat/test-geographicmap.R

Use https://github.com/Displayr/r-packages-orb/pull/38 to update rhtmlCombinedScatter (this is a workaround while the [docker image](https://app.circleci.com/insights/github/Displayr/r-server/workflows/build-nightly-docker-image/overview?branch=master) is broken)

Untracked: fix circle ci tests

---

DESCRIPTION
R/chartutils.R
tests/testthat/test-checkmatrixnames.R

This PR fixes 
1) duplicated rownames becoming uncentered, raised in https://displayr.slack.com/archives/C013HGKCK9V/p1723727828941759; and
2) NA rownames resulting in bars disappearing from bar/column charts

Untracked: fix strange behaviour of duplicates and NAs in rownames

---

R/combinedscatterplot.R

Sorry yet another fix. I found this one while going through the area chart diffs. This edge case bug only occurs when tick max num is specified for dates and the max bound is specified but not the min bound.

FS2-2826: Fix when tick max num is specified with a bound

---

DESCRIPTION
R/annotdata.R
R/barchart.R
R/columnchart.R
R/linechart.R
R/piechart.R
R/radarchart.R
R/stackedcolumnannot.R
tests/testthat/test-chartlabels.R

Currently, exported pie charts only show category names instead of the category names with values shown in Displayr. Here we explicitly specify the structure of the pie chart data labels so it matches what is shown in Displayr.

RS-17399: Fix pie chart labels for exporting

---

R/piechart.R
tests/testthat/test-chartlabels.R

Without this fix, custom prefix/suffix is only appended to the first label in the pie chart. I originally thought this was a bug in Displayr, but found a comment indicating pie chart data labels are handled differently to bar charts.

RS-17399: Fix exporting of customized pie chart labels

---

DESCRIPTION
R/combinedscatterplot.R
tests/testthat/test-combinedscatterplot.R

Previously, when `scatter.colors` is categorical, the color palette was not updated to remove empty color groups. This can cause problems when there are missing values in the data or if there are factor levels with no observations. This fix means that `CombinedScatter` behaves in the same way as `Scatter`

RS-18125: Fix handling of empty color categories in combined scatter

---

package.nix

As part of the R Server CI/CD uplift, this task is to package flipStandardCharts in Nix to make R server CI/CD more reliable and reproducible. To build it, see https://github.com/Displayr/NixR

DPI-2902 Package flipStandardCharts in nix

---

R/combinedscatterplot.R

This fixes the previous commit which was using numeric values (including negatives and floating points) to access the color vector.

RS-18125: Explicitly convert numeric scatter.colors to levels

---

R/combinedscatterplot.R
tests/testthat/test-combinedscatterplot.R

This change shouldn't cause visible changes. But for when scatter.colors is treated as categorical, the `colors` vector returned by `getColors` should match the legend exactly (both the colors and the series name) so we can check it without visual tests

RS-18125: Refactor to unit test getColors

---

R/distribution.R
tests/testthat/test-histogram.R

The warning message "no non-missing arguments to min" is not helpful and a bit distracting. The chart should now render without issues so there is enough visual feedback for the user to figure out what to do.

RS-16397: Suppress uninformative warning in histogram

---

DESCRIPTION
R/barchart.R
R/chartutils.R
tests/testthat/test-axis.R
tests/testthat/test-barpictograph.R

Most of the time, the default axis bounds are automatically determined by plotly, but for bar charts with data labels we manually override plotly defaults because plotly will sometimes not leave enough space on the x-axis for the data labels and truncate the labels instead. 
This PR fixes the axis bounds overrides for the case when all values are negative.

RS-19907: Fix default axis bounds for all-negative values
